### ISSUE TITLE
Twitter Module is trying to parse credentials file when it receive a STALE message from LS

### ISSUE THREAD

**Issue by rodrigopavezi** [Rise-Vision/twitter-module#39]
When twitter module receives a STALE update message for the credentials file it should not try to parse the file checking if file exists on LS before. Something like what is done on display control [here](https://github.com/Rise-Vision/display-control-module/blob/master/src/watch.js#L52)

**Comment by jungeunyoon** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [twitter-module -- Issue 39 ](https://trello.com/c/IW7nlxW9/5349-twitter-module-issue-39)

**Comment by rudibravo** [comment]
PR #40 to fix this issue has been approved and merged. Fix is rolled out to 100% today so I'm closing the issue. Thanks
