### ISSUE TITLE
Tweets don't show if user is using proxy

### ISSUE THREAD

**Issue by rudibravo** [Rise-Vision/twitter-module#45]
**What is the expected behavior?**
Tweets show up if the user has a proxy setup

**What is the actual behavior?**
Tweets show up correctly

**What steps can be taken to replicate the problem?**
Set a display to pro
Add Twitter to a Presentation and connect your account
Schedule Twitter to the display
Setup the display to [use proxy](https://help.risevision.com/hc/en-us/articles/115003749183-How-do-I-configure-Rise-Player-to-use-a-proxy-)
Tweets don't show up

**Comment by sheadarlison** [comment]
@rudibravo is this fixed with this change https://github.com/Rise-Vision/local-storage-module/pull/84 or does the twitter module need a similar change?

**Comment by rudibravo** [comment]
@sheadarlison twitter still needs to address proxy settings when using the API [here](https://github.com/Rise-Vision/twitter-module/blob/cb702ed7878040bb5a6f948f4e8402646eb7c5e7/src/api/twitter.js#L22)
[Here](https://github.com/desmondmorris/node-twitter/tree/master/examples#proxy) is the documentation from the client we are using

**Comment by sheadarlison** [comment]
Thanks @rudibravo !

**Comment by jungeunyoon** [comment]
### Problem 
Tweets don't display when user is using a proxy
### Solution 
Twitter Module should use common proxy URI encoding in `common-display-module`
### How to validate 
1. Set up proxy on display
2. Use presentation with Twitter Widget
