### ISSUE TITLE
Revoking Twitter does nothing, and regardless of handle, it always shows Rise on Licensed Displays

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/twitter-module#59]
### What is the expected behavior?
When you have a Licensed Display, it should show the handle selected in the Widget. 

The Widget should let you know when the credentials have been revoked.

### What is the actual behavior?
In this case, the Widget is always showing the Rise Vision handle on a Licensed Display in this users Company. 

Even thought they have revoked access to the Widget, it shows that the Widget has access.

### What steps can be taken to replicate the problem?
So far I can't recreate showing the incorrect handle in my Company, but this user has it.

**Comment by santiagonoguez** [comment]
The fix is now in master branch, and deployed, so no new presentations will be affected. 

We may still need to manually unlock credential files for affected presentations, so they can display custom tweets again.
