### ISSUE TITLE
Twitter component will not allow users to authenticate in the Twitter template

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/twitter-module#61]
### What is the expected behavior?
When you have not connected a Twitter account, when editing the Twitter Full Screen Template, you can "Edit" the Twitter component to connect a Twitter account.

### What is the actual behavior?
When you have not connected a Twitter account, when editing the Twitter Full Screen Template, clicking "Edit" on the Twitter Component and then "Connect to Twitter" returns an error: "We're having trouble connecting to your Twitter account."

### What steps can be taken to replicate the problem?
1. Make sure your twitter account is not already authenticated to Rise Vision.  https://help.twitter.com/en/managing-your-account/connect-or-revoke-access-to-third-party-apps
2. Create a new presentation from the Twitter Full Screen template
3. Click on "Edit" on the Twitter component
4. Attempt to Connect to Twitter
5. You'll receive the error "We're having trouble connecting to your Twitter account."

**Comment by stulees** [comment]
@PatrickA-RiseVision Tentative date for this to be resolved by is Feb 4th, please let me know if you have any concerns. Thanks

**Comment by stulees** [comment]
@PatrickA-RiseVision The refresh token for client authentication had apparently expired as I created a new refresh token and it has resolved the problem, see PR https://github.com/Rise-Vision/private-keys/pull/36. Closing, thanks.
